"use client";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const privacyContent = `## **PRIVACY POLICY**

**Last updated:** March 26, 2026

---

This Privacy Policy explains how **JustTalk AI, LLC** (“**JustTalk**,” “**we**,” “**us**,” or “**our**”) collects, uses, stores, shares, and otherwise processes personal information when you access or use our website, applications, and related services (collectively, the “**Service**”).

This Privacy Policy applies to information collected through JustTalk AI and should be read together with our Terms of Service. By accessing or using the Service, you acknowledge that you have read and understood this Privacy Policy.

---

## **1. Scope**

This Privacy Policy applies to personal information we collect when you:

- create an account;
- browse or interact with our website or applications;
- purchase a subscription or other paid services;
- participate in AI-powered lessons, voice sessions, messaging, or tutoring features;
- contact us for support or otherwise communicate with us.

For purposes of this Privacy Policy, **“personal information”** means information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular person or household.

---

## **2. Eligibility**

Our Service is intended only for individuals who are at least **18 years old**. We do not knowingly collect personal information from children under 18. If we learn that we have collected personal information from a person under 18, we may delete that information and suspend or terminate the associated account.

---

## **3. Information We Collect**

We collect the following categories of information, depending on how you use the Service.

### **3.1 Account and Registration Information**

When you create an account, we may collect:

- full name;
- email address;
- password;
- account role or profile details;
- other information you choose to add to your profile.

### **3.2 Subscription, Transaction, and Billing Information**

If you subscribe to a paid plan or purchase services, we may collect:

- subscription plan details;
- billing information;
- payment-related metadata;
- transaction history;
- billing country, postal code, and tax-related information where required.

Payment processing is handled by third-party payment processors. We do not store full payment card numbers ourselves.

### **3.3 Lesson, Tutoring, and Learning Information**

To provide the Service, we may collect and process information related to your learning activity, including:

- lesson history;
- teacher and student session data;
- messages exchanged through the Service;
- assignments, notes, prompts, and responses;
- audio recordings, voice inputs, speech transcriptions, and related analysis;
- pronunciation, grammar, vocabulary, fluency, and other learning feedback;
- progress history, performance insights, and recommendations generated by the Service.

### **3.4 User Content**

We collect the content you upload, submit, transmit, or otherwise make available through the Service (“**User Content**”), such as:

- text entries;
- messages;
- recordings;
- attachments;
- profile content;
- feedback you provide.

You retain ownership of your User Content, subject to the rights you grant us as described in our Terms of Service and this Privacy Policy.

### **3.5 Support and Communications Information**

If you contact us, we may collect:

- your name and email address;
- the contents of your message;
- support history;
- attachments or screenshots you send;
- any other information you choose to provide.

### **3.6 Automatically Collected Information**

When you access or use the Service, we may automatically collect certain information, such as:

- IP address;
- device identifiers;
- browser type and settings;
- operating system;
- referral URLs;
- language preferences;
- access dates and times;
- pages viewed and features used;
- log data, diagnostics, crash data, and performance metrics.

### **3.7 Information from Third Parties**

We may receive information from third parties, including:

- payment processors;
- analytics providers;
- authentication providers;
- hosting and infrastructure providers;
- customer support tools;
- integrated third-party services you choose to connect.

---

## **4. How We Collect Information**

We collect information:

- directly from you when you register, subscribe, use the Service, or contact us;
- automatically through cookies, logs, and similar technologies;
- from service providers and third-party integrations;
- from tutors, students, or other users where necessary to operate the Service.

---

## **5. How We Use Personal Information**

We use personal information for the following purposes:

### **5.1 To Provide the Service**

We use personal information to:

- create and maintain your account;
- authenticate users;
- provide AI-powered language learning features;
- enable tutoring, lesson scheduling, messaging, and session functionality;
- process speech, text, and other inputs in order to generate feedback and learning insights;
- personalize your experience;
- process purchases, subscriptions, renewals, and cancellations.

### **5.2 To Operate, Improve, and Develop the Service**

We use personal information to:

- analyze usage and trends;
- troubleshoot errors and maintain security;
- improve model performance, product features, and user experience;
- develop new tools, features, and educational functionality;
- conduct internal testing, analytics, research, and quality assurance.

### **5.3 To Communicate with You**

We use personal information to:

- send transactional and service-related messages;
- send account, billing, renewal, and support notices;
- respond to questions and requests;
- send updates about the Service;
- send marketing communications where permitted by law.

You can opt out of marketing emails at any time by using the unsubscribe link or contacting us.

### **5.4 To Protect Rights and Prevent Misuse**

We may use personal information to:

- detect, investigate, and prevent fraud, abuse, unauthorized access, and violations of our Terms;
- enforce our agreements and policies;
- protect the security, integrity, and availability of the Service;
- protect our rights, users, and business.

### **5.5 To Comply with Legal Obligations**

We may use personal information to comply with applicable laws, regulations, court orders, lawful requests, tax requirements, and legal processes.

---

## **6. Legal Bases for Processing (EEA/UK)**

If you are located in the European Economic Area or the United Kingdom, we process personal information under one or more of the following legal bases:

- **Performance of a contract**: where processing is necessary to provide the Service to you.
- **Legitimate interests**: where processing is necessary for our legitimate interests, such as improving the Service, securing the platform, preventing fraud, and communicating with users.
- **Consent**: where required by law, including for certain marketing activities or specific optional features.
- **Legal obligation**: where processing is necessary to comply with applicable law.

---

## **7. How We Share Personal Information**

We do **not sell** your personal information.

We may share personal information in the following limited circumstances:

### **7.1 Service Providers**

We share information with vendors and service providers that perform services on our behalf, such as:

- cloud hosting and storage providers;
- payment processors;
- analytics providers;
- authentication providers;
- customer support providers;
- communications and email tools;
- AI, transcription, moderation, and infrastructure providers.

These parties are authorized to use personal information only as necessary to provide services to us or as otherwise permitted by law.

### **7.2 Tutors and Other Users**

Where relevant to the Service, we may share certain information between students and tutors, such as:

- profile information;
- lesson history;
- session content;
- progress indicators;
- messages and materials shared through the platform.

### **7.3 Business Transfers**

We may disclose information in connection with an actual or proposed merger, financing, acquisition, restructuring, bankruptcy, sale of assets, or similar corporate transaction.

### **7.4 Legal and Safety Reasons**

We may disclose information if we believe doing so is necessary to:

- comply with law or legal process;
- respond to lawful requests from public authorities;
- enforce our Terms or other agreements;
- detect or prevent fraud, abuse, or security issues;
- protect the rights, property, or safety of JustTalk, our users, or others.

---

## **8. Audio, Voice, and AI Processing**

Because JustTalk includes language learning, tutoring, and AI-powered analysis features, we may process audio, voice, text, and related session content in order to:

- transcribe speech;
- generate pronunciation, grammar, fluency, or vocabulary feedback;
- provide lesson summaries and progress tracking;
- personalize future learning sessions;
- improve the quality, reliability, and safety of the Service.

We may use third-party providers to help process this data on our behalf, subject to appropriate contractual and security protections.

We do not access your content unless it is reasonably necessary for service delivery, support, safety, quality assurance, legal compliance, or enforcement of our Terms.

---

## **9. Cookies and Similar Technologies**

We use cookies, pixels, local storage, and similar technologies to:

- keep you signed in;
- remember preferences;
- analyze traffic and usage patterns;
- improve performance and usability;
- measure the effectiveness of communications;
- support security and fraud prevention.

You can control cookies through your browser settings. If you disable cookies, some features of the Service may not function properly.

---

## **10. Analytics and Advertising**

We may use analytics tools and similar technologies to understand how users interact with the Service and to improve our products and communications.

We may also work with third-party providers for marketing and measurement. These providers may use cookies or similar technologies, subject to their own privacy practices.

---

## **11. Data Retention**

We retain personal information for as long as reasonably necessary to:

- provide the Service;
- maintain your account;
- fulfill the purposes described in this Privacy Policy;
- comply with legal, tax, accounting, and regulatory obligations;
- resolve disputes;
- enforce our agreements.

We may retain backup copies and archived information for a limited period where required for operational, legal, or security reasons.

If you request deletion of your account, we will take reasonable steps to delete or de-identify your personal information, except where retention is required or permitted by law.

---

## **12. Data Security**

We use commercially reasonable administrative, technical, and physical safeguards designed to protect personal information from unauthorized access, disclosure, alteration, and destruction.

However, no method of transmission over the internet and no storage system is completely secure. As a result, we cannot guarantee absolute security.

You are responsible for maintaining the confidentiality of your credentials and for protecting access to your account.

---

## **13. International Data Transfers**

JustTalk AI, LLC is based in the United States, and we and our service providers may process personal information in the United States and other countries.

If you access the Service from outside the United States, your information may be transferred to and processed in jurisdictions that may not provide the same level of legal protection as your home jurisdiction.

Where required by law, we use appropriate safeguards for international data transfers.

---

## **14. Your Privacy Rights**

Depending on your location, you may have certain rights regarding your personal information, including the right to:

- access the personal information we hold about you;
- correct inaccurate or incomplete information;
- request deletion of your information;
- object to or restrict certain processing;
- withdraw consent where processing is based on consent;
- request data portability;
- opt out of marketing communications.

To exercise any applicable rights, contact us at **support@justtalk.ai**. We may need to verify your identity before processing your request.

---

## **15. California Privacy Notice**

If you are a California resident, you may have rights under the California Consumer Privacy Act, as amended, including the right to:

- know what categories of personal information we collect, use, disclose, and retain;
- request access to specific pieces of personal information;
- request deletion of personal information, subject to exceptions;
- correct inaccurate personal information;
- not be discriminated against for exercising your privacy rights.

We do not sell your personal information and do not share personal information for cross-context behavioral advertising in a manner that would require an opt-out under applicable California law, unless stated otherwise at the time of collection.

You may exercise your rights by contacting us at **support@justtalk.ai**.

---

## **16. EEA and UK Privacy Rights**

If you are located in the EEA or UK, you may have the right to:

- request access to your personal information;
- request correction or erasure;
- request restriction of processing;
- object to processing based on legitimate interests;
- request portability of certain information;
- withdraw consent where applicable;
- lodge a complaint with your local supervisory authority.

---

## **17. Third-Party Services**

The Service may contain links to third-party websites or integrate with third-party services. This Privacy Policy does not apply to third-party websites, products, or services, which are governed by their own terms and privacy policies.

We encourage you to review those third-party policies before using such services.

---

## **18. Changes to This Privacy Policy**

We may update this Privacy Policy from time to time. If we make material changes, we will post the updated version on our website and update the "Last updated" date above. Where required by law, we will provide additional notice.

Your continued use of the Service after the effective date of an updated Privacy Policy constitutes your acknowledgment of the revised Policy.

---

## **19. Contact Us**

If you have any questions about this Privacy Policy or wish to exercise your privacy rights, you may contact us at:

**JustTalk AI, LLC**  
**Email:** support@justtalk.ai  
**Website:** https://justtalk.ai
`;

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-just_white">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <article className="prose prose-lg max-w-none">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                h2: ({ children }) => (
                  <h2 className="text-2xl font-bold mt-12 mb-6 text-just_black">{children}</h2>
                ),
                h3: ({ children }) => (
                  <h3 className="text-xl font-semibold mt-8 mb-4 text-just_black">{children}</h3>
                ),
                p: ({ children }) => (
                  <p className="mb-6 text-just_black-7 leading-relaxed">{children}</p>
                ),
                ul: ({ children }) => (
                  <ul className="list-disc pl-6 mb-6 space-y-2">{children}</ul>
                ),
                li: ({ children }) => (
                  <li className="text-just_black-7">{children}</li>
                ),
                strong: ({ children }) => (
                  <strong className="font-semibold text-just_black">{children}</strong>
                ),
                hr: () => <hr className="my-8 border-just_cod-gray-5" />,
              }}
            >
              {privacyContent}
            </ReactMarkdown>
          </article>
        </div>
      </main>
      <Footer />
    </>
  );
}